"use client";
import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Bot, CheckCircle2, XCircle, Code2, Play, GitMerge, FileCode2 } from "lucide-react";
import Editor from "@monaco-editor/react";

export default function FixWorkspace() {
  const [workflowState, setWorkflowState] = useState<"detected" | "generating" | "review" | "approved" | "testing" | "validated">("detected");
  const searchParams = useSearchParams();
  const scanId = searchParams.get('scan_id');
  const issueId = searchParams.get('issue_id');
  
  const [issue, setIssue] = useState<any>(null);
  
  useEffect(() => {
    async function fetchIssue() {
      if (!scanId || !issueId) return;
      try {
        const res = await fetch(`http://localhost:8000/api/scans/${scanId}`);
        if (res.ok) {
          const data = await res.json();
          const found = data.issues?.find((i: any) => i.id === issueId);
          if (found) setIssue(found);
        }
      } catch(e) {}
    }
    fetchIssue();
  }, [scanId, issueId]);

  const originalCode = issue?.code_snippet || issue?.code || `// Vulnerable to SQL injection\nconst query = \`SELECT * FROM users WHERE username = '\${req.body.username}'\`;\nconst result = await db.execute(query);`;
  
  // Generate a realistic fixed code diff
  let fixedCode = originalCode;
  if (fixedCode.includes("SELECT")) {
    fixedCode = fixedCode.replace(/\+.*$/, "").replace(/f['"].*\{.*\}['"]/, "'SELECT * FROM users WHERE username = %s', (username,)").replace(/`SELECT.*`/g, "`SELECT * FROM users WHERE username = $1`, [req.body.username]");
  }
  if (fixedCode.toLowerCase().includes("secret") || fixedCode.toLowerCase().includes("password") || fixedCode.toLowerCase().includes("api_key")) {
    fixedCode = fixedCode.replace(/['"][a-zA-Z0-9_-]{5,}['"]/g, "process.env.SECRET_KEY || os.environ.get('SECRET_KEY')");
  }
  if (fixedCode.includes("http://")) {
    fixedCode = fixedCode.replace(/http:\/\//g, "https://");
  }
  if (fixedCode.includes("while") || fixedCode.includes("retry")) {
    fixedCode = fixedCode.replace(/while\s*\(?true\)?\s*:/ig, "for attempt in range(MAX_RETRIES):").replace(/while.*\{/i, "let retryCount = 0;\nwhile (retryCount < MAX_RETRIES) {");
  }
  
  fixedCode = `// ✅ AI Proposed Fix\n// ${issue?.recommended_fix || issue?.fix || 'Refactored to prevent vulnerability.'}\n\n` + fixedCode;

  const handleGenerate = () => {
    setWorkflowState("generating");
    setTimeout(() => setWorkflowState("review"), 2000);
  };

  const handleApprove = () => {
    setWorkflowState("approved");
  };

  const handleGenerateTests = () => {
    setWorkflowState("testing");
    setTimeout(() => setWorkflowState("validated"), 3000);
  };

  return (
    <div className="container mx-auto px-4 py-8 h-[calc(100vh-80px)] flex flex-col">
      <div className="mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-space-grotesk font-bold flex items-center gap-3">
            <Bot className="w-8 h-8 text-accent" /> AI-Assisted Remediation
          </h1>
          <p className="text-text-secondary mt-1">Review and approve fixes generated by IBM Bob.</p>
        </div>
        
        {/* Workflow Status */}
        <div className="hidden lg:flex items-center gap-2 text-xs font-semibold bg-secondary px-4 py-2 rounded-full border border-card-border">
          <span className={workflowState === "detected" ? "text-primary" : "text-success"}>Issue Detected</span>
          <span className="text-text-secondary/30">→</span>
          <span className={workflowState === "generating" ? "text-primary animate-pulse" : workflowState === "detected" ? "text-text-secondary" : "text-success"}>Fix Generated</span>
          <span className="text-text-secondary/30">→</span>
          <span className={workflowState === "review" ? "text-primary" : ["approved", "testing", "validated"].includes(workflowState) ? "text-success" : "text-text-secondary"}>Human Review</span>
          <span className="text-text-secondary/30">→</span>
          <span className={workflowState === "testing" ? "text-primary animate-pulse" : workflowState === "validated" ? "text-success" : "text-text-secondary"}>Tests Executed</span>
          <span className="text-text-secondary/30">→</span>
          <span className={workflowState === "validated" ? "text-success" : "text-text-secondary"}>Validation</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 flex-grow min-h-0">
        
        {/* Left Panel - Issue context */}
        <div className="lg:col-span-1 bg-card border border-white/5 rounded-2xl p-6 flex flex-col overflow-y-auto custom-scrollbar">
          <div className="mb-6 pb-6 border-b border-white/5">
            <span className="text-xs font-bold px-2 py-1 rounded-md bg-critical/20 text-critical mb-3 inline-block">Critical</span>
            <h3 className="font-bold text-lg mb-2">SQL Injection Vulnerability</h3>
            <p className="text-sm text-text-secondary">User input is concatenated directly into the SQL query without parameterization.</p>
            <div className="mt-4 flex items-center gap-2 text-xs font-mono text-text-secondary bg-secondary px-2 py-1 rounded">
              <FileCode2 className="w-3 h-3" /> db_queries.ts:42
            </div>
          </div>

          <div className="mb-6">
            <h4 className="font-semibold text-sm mb-2 text-critical">Potential Impact</h4>
            <p className="text-xs text-text-secondary">Attackers can execute arbitrary SQL commands, potentially reading or modifying sensitive data.</p>
          </div>

          <div className="mt-auto">
            {workflowState === "detected" && (
              <button 
                onClick={handleGenerate}
                className="w-full bg-accent hover:bg-accent/90 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-[0_0_15px_rgba(139,92,246,0.3)]"
              >
                <Bot className="w-5 h-5" /> Generate Fix with AI
              </button>
            )}
            
            {workflowState === "generating" && (
              <button disabled className="w-full bg-secondary text-text-secondary py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all opacity-50 cursor-not-allowed">
                <Bot className="w-5 h-5 animate-pulse text-accent" /> Analyzing with IBM Bob...
              </button>
            )}

            {workflowState === "review" && (
              <div className="flex gap-2">
                <button onClick={handleApprove} className="flex-1 bg-success hover:bg-success/90 text-background py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all shadow-[0_0_15px_rgba(34,197,94,0.2)]">
                  <CheckCircle2 className="w-5 h-5" /> Approve
                </button>
                <button onClick={() => setWorkflowState("detected")} className="flex-1 bg-card border border-card-border hover:border-critical text-foreground py-3 rounded-xl font-bold flex items-center justify-center gap-2 transition-all">
                  <XCircle className="w-5 h-5 text-critical" /> Reject
                </button>
              </div>
            )}

            {["approved", "testing", "validated"].includes(workflowState) && (
              <div className="p-4 bg-success/10 border border-success/30 rounded-xl text-center">
                <CheckCircle2 className="w-8 h-8 text-success mx-auto mb-2" />
                <p className="text-sm font-semibold text-success">Fix Approved</p>
              </div>
            )}
          </div>
        </div>

        {/* Center Panel - Diff View */}
        <div className="lg:col-span-2 bg-[#1e1e1e] border border-white/5 rounded-2xl flex flex-col relative overflow-hidden">
          <div className="bg-[#2d2d2d] px-4 py-3 flex items-center justify-between border-b border-[#404040]">
            <div className="text-xs font-semibold text-foreground flex items-center gap-2">
              <GitMerge className="w-4 h-4 text-accent" /> Code Diff Review
            </div>
            {workflowState === "generating" && <div className="text-xs text-accent animate-pulse font-mono">IBM Bob is typing...</div>}
          </div>
          
          <div className="flex-grow flex flex-col">
            <div className="flex-1 relative border-b border-[#404040]/50">
              <div className="absolute top-0 left-0 bg-critical/20 text-critical text-[10px] px-2 py-0.5 rounded-br-lg z-10 font-bold uppercase tracking-wider">Original</div>
              <Editor
                height="100%"
                language="typescript"
                theme="vs-dark"
                value={originalCode}
                options={{ readOnly: true, minimap: { enabled: false }, scrollBeyondLastLine: false, fontSize: 13 }}
              />
            </div>
            <div className="flex-1 relative">
              <div className="absolute top-0 left-0 bg-success/20 text-success text-[10px] px-2 py-0.5 rounded-br-lg z-10 font-bold uppercase tracking-wider">Proposed Fix</div>
              <Editor
                height="100%"
                language="typescript"
                theme="vs-dark"
                value={["review", "approved", "testing", "validated"].includes(workflowState) ? fixedCode : "// Waiting for AI analysis..."}
                options={{ readOnly: true, minimap: { enabled: false }, scrollBeyondLastLine: false, fontSize: 13 }}
              />
            </div>
          </div>
        </div>

        {/* Right Panel - Tests */}
        <div className="lg:col-span-1 bg-card border border-white/5 rounded-2xl p-6 flex flex-col overflow-y-auto custom-scrollbar">
          <h3 className="font-semibold mb-4 flex items-center gap-2">
            <CheckCircle2 className="w-5 h-5 text-primary" /> Regression Tests
          </h3>

          <AnimatePresence>
            {workflowState === "approved" && (
              <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-6 p-4 bg-primary/10 border border-primary/30 rounded-xl">
                <p className="text-sm text-foreground mb-4">Fix applied. You should run regression tests to validate the change.</p>
                <button onClick={handleGenerateTests} className="w-full bg-primary hover:bg-primary/90 text-background py-2 rounded-lg font-semibold flex items-center justify-center gap-2 transition-all">
                  <Play className="w-4 h-4" /> Generate & Run Tests
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          {(workflowState === "testing" || workflowState === "validated") && (
            <div className="space-y-4">
              {[
                { name: "SQL Injection Resistance", desc: "Injecting SQL payloads does not alter logic.", status: workflowState === "validated" ? "passed" : "running" },
                { name: "Valid User Retrieval", desc: "Valid usernames still return data.", status: workflowState === "validated" ? "passed" : "running" },
              ].map((test, idx) => (
                <div key={idx} className="p-3 bg-secondary rounded-lg border border-white/5">
                  <div className="flex items-center justify-between mb-1">
                    <h5 className="font-semibold text-sm">{test.name}</h5>
                    {test.status === "passed" ? (
                      <CheckCircle2 className="w-4 h-4 text-success" />
                    ) : (
                      <div className="w-4 h-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />
                    )}
                  </div>
                  <p className="text-xs text-text-secondary">{test.desc}</p>
                </div>
              ))}

              {workflowState === "validated" && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-6 pt-6 border-t border-white/5 text-center">
                  <div className="inline-flex items-center gap-2 bg-success/20 text-success px-4 py-2 rounded-full text-sm font-bold mb-4">
                    <CheckCircle2 className="w-4 h-4" /> All Tests Passed
                  </div>
                  <p className="text-xs text-text-secondary">The code changes have been validated and are ready for release review.</p>
                </motion.div>
              )}
            </div>
          )}

          {["detected", "generating", "review"].includes(workflowState) && (
            <div className="h-full flex items-center justify-center text-text-secondary opacity-30 text-sm text-center">
              Approve the fix to generate regression tests.
            </div>
          )}

        </div>

      </div>
    </div>
  );
}
